### ISSUE TITLE
prepareDatabase('accessionTaxa.sql') - Error in utils::download.file(url, tarFile, mode = "wb") :    cannot open URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'

### ISSUE THREAD

**Issue by David-Madrigal** [sherrillmix/taxonomizr#27] opened 2021-03-16 23:36 UTC
Hi!

I've downloaded the library, and I'm trying to do the prepareDatabase step. When running `prepareDatabase('accessionTaxa.sql')` I get the following message:

```
Downloading names and nodes with getNamesAndNodes()
trying URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'
Content type 'unknown' length 54625551 bytes (52.1 MB)
================
Error in utils::download.file(url, tarFile, mode = "wb") : 
  cannot open URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'
In addition: Warning messages:
1: In utils::download.file(url, tarFile, mode = "wb") :
  downloaded length 17669944 != reported length 54625551
2: In utils::download.file(url, tarFile, mode = "wb") :
  URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz': status was 'Transferred a partial file'
```

Is it a problem with NCBI networking? Or something else?
Thanks in advance!

**Comment by sherrillmix** [comment] 2021-03-17 12:10
Are you on an older version of taxonomizr (and slow internet)? If you run:
`packageVersion('taxonomizr')`
it should show 0.6.0. 

Older versions run into a time out "feature" in R where any download longer than a minute is silently cut off at one minute e.g. issue #25. 

If updating and rerunning doesn't fix it then I'll guess it'll need some debugging. Maybe paste in `sessionInfo()` to start to narrow things down.

**Comment by David-Madrigal** [comment] 2021-03-17 16:38
I'm currently running 0.6.0 version of taxonomizr.

running `sessionInfo()` displays the following:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxonomizr_0.6.0

loaded via a namespace (and not attached):
[1] compiler_4.0.2    tools_4.0.2       data.table_1.14.0
```

**Comment by sherrillmix** [comment] 2021-03-17 16:59
This looks to be a problem with the `getNamesAndNodes()` step (at least initially). If you run it by itself:

```
getNamesAndNodes()
```

what happens?

And if you visit ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz in browser (or `wget` from terminal) do you get the complete file? It should have the same md5 as specified in ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz.md5 .

**Comment by David-Madrigal** [comment] 2021-03-17 17:57
I've changed Wi-Fi network to check if that was the source of the problem. Running either `prepareDatabase('accessionTaxa.sql')` or `getNamesAndNodes()` by itself displays the following message (it's differs from before):

```
trying URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'
Content type 'unknown' length 54658009 bytes (52.1 MB)
==================================================
Error in utils::download.file(url, tarFile, mode = "wb") : 
  cannot open URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz'
In addition: Warning message:
In utils::download.file(url, tarFile, mode = "wb") :
  cannot open URL 'ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz': FTP status was '450 Requested file action not taken'
```

Running `wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz` downloads the complete file. No error messages are displayed when running:

```
--2021-03-17 11:24:43--  ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
           => 'taxdump.tar.gz'
Resolving ftp.ncbi.nih.gov... 130.14.250.13, 130.14.250.12
Connecting to ftp.ncbi.nih.gov|130.14.250.13|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/taxonomy ... done.
==> SIZE taxdump.tar.gz ... 54658009
==> PASV ... done.    ==> RETR taxdump.tar.gz ... done.
Length: 54658009 (52M) (unauthoritative)

taxdump.tar.gz       100%[===================>]  90.96M   603KB/s    in 3m 5s   

2021-03-17 11:27:49 (505 KB/s) - 'taxdump.tar.gz' saved [95382585]
```

**Comment by sherrillmix** [comment] 2021-03-17 18:27
Hmm. Very odd. Thanks for all the debugging. Since you did manage to get the files, worst case you could extract the `names.dmp` and `nodes.dmp` from it and put them in the directory you're working in. Then the `prepareDatabase()` command should just skip over the `getNamesAndNodes()` step if the files already exist (or you could follow the "Manual preparation of database (usually not necessary)" of the README and just skip the `getNamesAndNodes` step).

But it's very weird that the download is not working. To try and trace it back a bit, could you try taking `taxonomizr` out of the equation and calling directly to:

```
    utils::download.file('ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz', 'taxdump.tar.gz', mode = "wb")
```

If that works, maybe one more shot with `getNamesAndNodes()` to make sure some transient NCBI bug hasn't been fixed in the mean time.  

And if it didn't work, maybe try:

```
    utils::download.file('ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz.md5', 'taxdump.tar.gz.md5', mode = "wb")
```

to see if a small file works.

**Comment by Jiulong-Zhao** [comment] 2021-03-18 15:14
Hi @sherrillmix ，
I met the same problem mentioned here!

Like @David-Madrigal said, the running "wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz" was successful. 

But the unzipped files of taxdump.tar.gz contain "names.dmp", "delnodes.dmp"... No file named "nodes.dmp"! I tried to rename the "delnodes.dmp" into "nodes.dmp" manually, and the ''prepareDatabase('accessionTaxa.sql')'' unexpectedly skip over the getNamesAndNodes() step like you said. Is this right?

As you suggested: 
Running:
`utils::download.file('ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz', 'taxdump.tar.gz', mode = "wb")`
also failed!

Running:
`utils::download.file('ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz.md5', 'taxdump.tar.gz.md5', mode = "wb")`
it can work!

So, what do you think is the reason for this bug? How to fix it?
Now, the "ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid//nucl_gb.accession2taxid.gz'" is being downloaded! 
Hope it can work!

Thanks for your effect on this Rscript!

Best wishes!
Jiulong

**Comment by sherrillmix** [comment] 2021-03-18 15:33
Hmm definitely does seem to be a pattern then. So if:

```
 utils::download.file('ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz', 'taxdump.tar.gz', mode = "wb")
```

fails then it seems like it's something upstream of `taxonomizr`. Except does the download take longer than a minute for you?

How about if you set the download timeout so that it only times out after an hour:

```
  options('timeout'=3600)
  utils::download.file('ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz', 'taxdump.tar.gz', mode = "wb")
```

Does it complete then? I set the timeout within the function (assuming you're using v0.6.0) so that wouldn't explain why getNamesAndNodes is failing but at least would narrow things a bit. 

And for the taxdump.tar.gz, I just downloaded it and see both names.dmp and nodes.dmp among a bunch of extra stuff e.g.:
![taxdump](https://user-images.githubusercontent.com/1217152/111651792-ecc7bd00-87dc-11eb-8225-138c14bd98dd.png)
Could you send the full list you're seeing? In any case, (although a good guess) I would probably not rename delnodes.dmp to nodes.dmp since from the name I assume it's all the junk that NCBI has deleted.

**Comment by David-Madrigal** [comment] 2021-03-18 18:22
Hi @sherrillmix!

Although running the `wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz` was "successful", the file was corrupted when I tried to gunzip. Nevertheless, `wget https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz` downloaded the file correctly, and I could extract the required files. Same thing with the `getAccession2taxid()` step. I've changed the 'ftp' to 'https' in order to download it on terminal. The following steps on `prepareDatabase('accessionTaxa.sql')` run without any issue after that. 

Previously, I've had problems with FTP... Maybe that's why `getNamesAndNodes()` had problems attempting to do the download and also the fact that I've got a corrupted file when running `wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz`.

Thank you so much for your help!

**Comment by sherrillmix** [comment] 2021-03-18 19:21
Hmm that's a weird one that ftp corrupts and https doesn't. I wonder what's going on. I wonder if 

```
getNamesAndNodes(url='https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz')
```

would have worked for you then. 

In any case, thanks for letting me know. I'll have to include that in debugging going forward.

**Comment by sherrillmix** [comment] 2021-03-24 22:54
Going to close but feel free to reopen if any more problems or information.

**Closed as completed by sherrillmix** 2021-03-24 22:54 UTC

**Comment by wanjauk** [comment] 2021-05-26 14:01
Hello @sherrillmix. The error in this issue is caused by the use of the FTP protocol to download the files from NCBI. Some functions in the package have an argument that takes a default URL value such as `ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz`. Changing the default URL value to `https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz` to use the HTTPS protocol solves the issue. I will send a pull request for you to have a look.
